/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestiondocumentalfesc.vistas;

import static com.mycompany.gestiondocumentalfesc.RenderImgJTable.ControladorTabla.copyFile;
import com.mycompany.gestiondocumentalfesc.conexion.Conexion;
import com.mycompany.gestiondocumentalfesc.modelos.Destinatario;
import com.mycompany.gestiondocumentalfesc.modelos.EmpresaRemitente;
import com.mycompany.gestiondocumentalfesc.modelos.EstudianteRemitente;
import com.mycompany.gestiondocumentalfesc.modelos.ListadoDestinatarios;
import com.mycompany.gestiondocumentalfesc.modelos.ListadoEmpresas;
import com.mycompany.gestiondocumentalfesc.modelos.ListadoEstudiantes;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


public class JFrameRegistrarDocumento extends javax.swing.JFrame {

    Conexion conexion = new Conexion();
    Connection connection = conexion.conectar();
    
    public JFrameRegistrarDocumento() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarComboEstudiante(jcbxSeleccionarEstudiante);
        cargarComboEmpresa(jcbxSeleccionarEmpresa);
        cargarComboDestinatario(jcbxSeleccionarDestinatario);
        jcbxSeleccionarEstudiante.addItem("Ninguno");
        jcbxSeleccionarEmpresa.addItem("Ninguno");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbConsultar = new javax.swing.JLabel();
        lbCerrarSesion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtAsunto = new javax.swing.JTextField();
        txtNumeroRadicado = new javax.swing.JTextField();
        txtNumeroAnexos = new javax.swing.JTextField();
        jDateFecha = new com.toedter.calendar.JDateChooser();
        jcbxTipoRadicado = new javax.swing.JComboBox<>();
        jcbxTipoDocumento = new javax.swing.JComboBox<>();
        jcbxSeleccionarEstudiante = new javax.swing.JComboBox<>();
        jcbxSeleccionarEmpresa = new javax.swing.JComboBox<>();
        jcbxSeleccionarDestinatario = new javax.swing.JComboBox<>();
        jBotonSeleccionarArchivo = new javax.swing.JButton();
        txtRutaArchivo = new javax.swing.JTextField();
        jcbRequiereRespuesta = new javax.swing.JCheckBox();
        jBotonAgregarRemitentes = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        panel1 = new java.awt.Panel();
        jLabel3 = new javax.swing.JLabel();
        jBotonSubirDatos = new javax.swing.JToggleButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GESTION DOCUMENTAL");

        lbConsultar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbConsultar.setForeground(new java.awt.Color(255, 255, 255));
        lbConsultar.setText("Consultar");
        lbConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbConsultarMouseClicked(evt);
            }
        });

        lbCerrarSesion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        lbCerrarSesion.setText("Cerrar sesion");
        lbCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                .addComponent(lbConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCerrarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, -1));

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Registrar datos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(637, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel2)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 760, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtAsunto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtAsunto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Asunto", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12))); // NOI18N

        txtNumeroRadicado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNumeroRadicado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Numero Radicado", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12))); // NOI18N

        txtNumeroAnexos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtNumeroAnexos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Numero Anexos", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jDateFecha.setBackground(new java.awt.Color(255, 255, 255));
        jDateFecha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12))); // NOI18N
        jDateFecha.setDateFormatString("yyyy-MM-dd");

        jcbxTipoRadicado.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcbxTipoRadicado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrega", "Respuesta" }));
        jcbxTipoRadicado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de radicado", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jcbxTipoDocumento.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcbxTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Carta", "Acta", "Copia", "Peticion", "Solicitud", "Derecho de peticion", "Citacion", "Memorando", "Caja", "Factura", "Remision", "Paquete", "Otro" }));
        jcbxTipoDocumento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de documento", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jcbxSeleccionarEstudiante.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcbxSeleccionarEstudiante.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estudiante remitente", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jcbxSeleccionarEmpresa.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcbxSeleccionarEmpresa.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Empresa remitente", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jcbxSeleccionarDestinatario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcbxSeleccionarDestinatario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Destinatario", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jBotonSeleccionarArchivo.setBackground(new java.awt.Color(240, 240, 240));
        jBotonSeleccionarArchivo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBotonSeleccionarArchivo.setText("Seleccionar archivo");
        jBotonSeleccionarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonSeleccionarArchivoActionPerformed(evt);
            }
        });

        txtRutaArchivo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jcbRequiereRespuesta.setBackground(new java.awt.Color(255, 255, 255));
        jcbRequiereRespuesta.setFont(new java.awt.Font("Arial", 3, 12)); // NOI18N
        jcbRequiereRespuesta.setText("Requiere Respuesta");

        jBotonAgregarRemitentes.setBackground(new java.awt.Color(255, 0, 0));
        jBotonAgregarRemitentes.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jBotonAgregarRemitentes.setForeground(new java.awt.Color(255, 255, 255));
        jBotonAgregarRemitentes.setText("+Nuevos remitentes y destinatarios");
        jBotonAgregarRemitentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonAgregarRemitentesActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        panel1.setBackground(new java.awt.Color(255, 0, 0));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Archivos Adjuntos");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jBotonSubirDatos.setBackground(new java.awt.Color(255, 0, 0));
        jBotonSubirDatos.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jBotonSubirDatos.setForeground(new java.awt.Color(255, 255, 255));
        jBotonSubirDatos.setText("SUBIR DATOS");
        jBotonSubirDatos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBotonSubirDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonSubirDatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jDateFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                                    .addComponent(txtAsunto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNumeroRadicado)
                                    .addComponent(jcbxTipoRadicado, 0, 240, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNumeroAnexos, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbxTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jBotonSeleccionarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtRutaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jcbxSeleccionarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbxSeleccionarEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jBotonAgregarRemitentes)
                                .addGap(121, 121, 121)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jcbRequiereRespuesta)
                                .addGap(109, 109, 109))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jcbxSeleccionarDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
            .addComponent(jSeparator2)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBotonSubirDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(297, 297, 297))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAsunto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroAnexos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroRadicado, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDateFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbxTipoRadicado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jcbxTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbxSeleccionarEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbxSeleccionarEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbxSeleccionarDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotonAgregarRemitentes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbRequiereRespuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBotonSeleccionarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRutaArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBotonSubirDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 760, 420));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 760, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbConsultarMouseClicked
        JFrameConsultar rgf = new JFrameConsultar();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_lbConsultarMouseClicked

    private void jBotonAgregarRemitentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonAgregarRemitentesActionPerformed
        JFrameRegistrarEntidades rgf = new JFrameRegistrarEntidades();
        rgf.setVisible(true);
        rgf.pack();
        rgf.setLocationRelativeTo(null);
        rgf.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
        
    }//GEN-LAST:event_jBotonAgregarRemitentesActionPerformed

    private void jBotonSeleccionarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonSeleccionarArchivoActionPerformed
        
        JFileChooser escoger = new JFileChooser();

        escoger.setFileSelectionMode(JFileChooser.FILES_ONLY);

        int estado = escoger.showOpenDialog(null);

        if(estado == JFileChooser.APPROVE_OPTION) {
            File archivo = escoger.getSelectedFile();
            if((archivo == null || (archivo.getName().equals("")))) {
                txtRutaArchivo.setText("...");
            }
            else {
                txtRutaArchivo.setText(archivo.getAbsolutePath());
            }
            File directorio = new File("C:\\archivos");
        
        
        if (!directorio.exists()) {
           directorio.mkdir();     
        }
            try {
                File pdfDes = new File(directorio.getAbsolutePath()+ "\\" +archivo.getName());
                copyFile(archivo,pdfDes);
                
            } catch (IOException ex) {
                    System.out.println("Error al subir el archivo");
            }
        }
    }//GEN-LAST:event_jBotonSeleccionarArchivoActionPerformed

    private void jBotonSubirDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonSubirDatosActionPerformed
            String sql;
            String asunto = txtAsunto.getText();
            String numRadicado = txtNumeroRadicado.getText();
            String tipoRadicado = jcbxTipoRadicado.getSelectedItem().toString();
            String fecha = ((JTextField)jDateFecha.getDateEditor().getUiComponent()).getText();
            String numAnexo = txtNumeroAnexos.getText();
            String tipoDocumento = jcbxTipoDocumento.getSelectedItem().toString();
            String selecEstudiante = jcbxSeleccionarEstudiante.getSelectedItem().toString();
            String selecEmpresa = jcbxSeleccionarEmpresa.getSelectedItem().toString();
            String selecDestinatario = jcbxSeleccionarDestinatario.getSelectedItem().toString();
            String reqRespuesta = getJhxReqRespuesta();
            
            sql = "INSERT INTO `documento`(`idDocumento`, `asunto`, `numeroRadicado`, `numeroAnexo`, `fecha`, `tipoRadicado`, `tipoDocumento`, `estudianteNombre`, `empresaNombre`, `destinatarioNombre`, `reqRespuesta`) VALUES (null,?,?,?,?,?,?,?,?,?,?)";
            
            try {
                PreparedStatement ps = connection.prepareStatement(sql);
                ps.setString(1, asunto);
                ps.setString(2, numRadicado);
                ps.setString(3, numAnexo);
                ps.setDate(4, (Date) Date.valueOf(fecha));
                ps.setString(5, tipoRadicado);
                ps.setString(6, tipoDocumento);
                ps.setString(7, selecEstudiante);
                ps.setString(8, selecEmpresa);
                ps.setString(9, selecDestinatario);
                ps.setString(10, reqRespuesta);
                int consulta4 = ps.executeUpdate();
                
                if(consulta4 > 0) {
                    JOptionPane.showMessageDialog(null, "Datos del documento subidos con exito"); 
                    actualizar();
                }
                else {
                    JOptionPane.showMessageDialog(null, "No se permiten campos vacios");
                }
                
            } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Error al subir datos " + e.getMessage());
        }
    }//GEN-LAST:event_jBotonSubirDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameRegistrarDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameRegistrarDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameRegistrarDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameRegistrarDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameRegistrarDocumento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBotonAgregarRemitentes;
    public javax.swing.JButton jBotonSeleccionarArchivo;
    public javax.swing.JToggleButton jBotonSubirDatos;
    public com.toedter.calendar.JDateChooser jDateFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JCheckBox jcbRequiereRespuesta;
    public javax.swing.JComboBox<String> jcbxSeleccionarDestinatario;
    public javax.swing.JComboBox<String> jcbxSeleccionarEmpresa;
    public javax.swing.JComboBox<String> jcbxSeleccionarEstudiante;
    public javax.swing.JComboBox<String> jcbxTipoDocumento;
    public javax.swing.JComboBox<String> jcbxTipoRadicado;
    public javax.swing.JLabel lbCerrarSesion;
    public javax.swing.JLabel lbConsultar;
    private java.awt.Panel panel1;
    public javax.swing.JTextField txtAsunto;
    public javax.swing.JTextField txtNumeroAnexos;
    public javax.swing.JTextField txtNumeroRadicado;
    public javax.swing.JTextField txtRutaArchivo;
    // End of variables declaration//GEN-END:variables

    private void cargarComboEstudiante(JComboBox c) {
        
        DefaultComboBoxModel comboEstudiante = new DefaultComboBoxModel();
        c.setModel(comboEstudiante);
        ListadoEstudiantes listadoEstudiantes = new ListadoEstudiantes();
        
        String sql = "SELECT CONCAT(docEstudiante,' - ', nombresEstudiante) FROM estudiante ORDER BY idEstudiante DESC";
        try {
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while (rs.next()) {
                EstudianteRemitente estudiante = new EstudianteRemitente();
                estudiante.setNombres(rs.getString(1));
                listadoEstudiantes.agregarEstudiantes(estudiante);
                comboEstudiante.addElement(estudiante.getNombres());
                
                System.out.println("Datos de estudiantes cargados con exito");
            }
        } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Error, no se puede cargar datos" + e.getMessage());
        }
    }

    private void cargarComboEmpresa(JComboBox c) {
        
        DefaultComboBoxModel comboEmpresa = new DefaultComboBoxModel();
        c.setModel(comboEmpresa);
        ListadoEmpresas listadoEmpresas = new ListadoEmpresas();
        
        String sql = "SELECT CONCAT(docEmpresa,' - ', nombreEmpresa) FROM empresa ORDER BY idEmpresa DESC";
        
        try {
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while(rs.next()) {
                EmpresaRemitente empresa = new EmpresaRemitente();
                empresa.setNombreEmpresa(rs.getString(1));
                listadoEmpresas.agregarEmpresas(empresa);
                comboEmpresa.addElement(empresa.getNombreEmpresa());
                
                System.out.println("Datos de empresas cargados con exito");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error, no se puede cargar datos" + e.getMessage());
        }
    }

    private void cargarComboDestinatario(JComboBox c) {
        
        DefaultComboBoxModel comboDestinatario = new DefaultComboBoxModel();
        c.setModel(comboDestinatario);
        ListadoDestinatarios listadoDestinatarios = new ListadoDestinatarios();
        
        String sql = "SELECT CONCAT(docDestinatario, ' - ', nombreDestinatario) FROM destinatario ORDER BY idDestinatario DESC";
        
        try {
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(sql);
            
            while (rs.next()) {
                Destinatario destinatario = new Destinatario();
                destinatario.setNombres(rs.getString(1));
                listadoDestinatarios.agregarDestinatarios(destinatario);
                comboDestinatario.addElement(destinatario.getNombres());
                
                System.out.println("Datos de destinatarios cargados con exito");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error, no se puede cargar datos" + e.getMessage());
        }
    }

    private String getJhxReqRespuesta() {
        if(jcbRequiereRespuesta.isSelected()) {
            return "1";
        }
        else {
            return "0";
        }
    }

    private void actualizar() {
        JFrameRegistrarDocumento main = new JFrameRegistrarDocumento();
        main.setVisible(true);
        this.dispose(); 
    }

}
